replicaCount: 1
image:
  repository: docker.elastic.co/integrations/elastic-connectors
  tag: 9.1.2

env:
  BUCKET_NAME: pbcore-json-aapb-dev
  TARGET_INDEX: aapb-catalog
  SCHEDULE: "*/30 * * * *"
  PYTHONHTTPSVERIFY: "0"
  