apiVersion: v2
name: prometheus
version: 0.0.1
appVersion: 3.2.1
description: Prometheus monitoring system
dependencies:
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 27.41.1
