apiVersion: v2
name: mla-eck-kibana
description: Wrapper chart for Kibana (via ECK)
type: application
version: 0.2.3
appVersion: 9.1.2

dependencies:
- name: eck-kibana
  version: 0.16.0
  repository: https://helm.elastic.co
