eck-kibana:
  version: 9.1.2
  elasticsearchRef:
    name: mla-eck-elasticsearch
    namespace: es
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
    - host: serarch.dev.wgbh-mla.org
      path: /
    tls:
      enabled: true
      secretName: mla-eck-kibana-tls
