apiVersion: v2
name: mla-eck-elasticsearch
description: Wrapper chart for Elasticsearch cluster (via ECK)
type: application
version: 0.2.2
appVersion: 9.1.2

dependencies:
- name: eck-elasticsearch
  version: 0.16.0
  repository: https://helm.elastic.co
